class CricketExecutor {

public static void main(String[] args) {

Cricket c1 = new Cricket();

c1.playerName = "Virat";
c1.playerNumber = 1;
c1.team = "RCB";
c1.role = "Batsman";
c1.matches = 250;
c1.runs = 12000;
c1.wickets = 4;
c1.strikeRate = 138.5;
c1.average = 52.4;
c1.centuries = 45;
c1.halfCenturies = 65;
c1.catches = 120;
c1.runOuts = 20;
c1.country = "India";
c1.age = 35;
c1.battingStyle = "Right Hand";
c1.bowlingStyle = "Right Arm Medium";
c1.jerseyNumber = 18;
c1.stadium = "Chinnaswamy";
c1.ranking = 1;

System.out.println(c1.playerName);
System.out.println(c1.playerNumber);
System.out.println(c1.team);
System.out.println(c1.role);
System.out.println(c1.matches);
System.out.println(c1.runs);
System.out.println(c1.wickets);
System.out.println(c1.strikeRate);
System.out.println(c1.average);
System.out.println(c1.centuries);
System.out.println(c1.halfCenturies);
System.out.println(c1.catches);
System.out.println(c1.runOuts);
System.out.println(c1.country);
System.out.println(c1.age);
System.out.println(c1.battingStyle);
System.out.println(c1.bowlingStyle);
System.out.println(c1.jerseyNumber);
System.out.println(c1.stadium);
System.out.println(c1.ranking);

Cricket c2 = new Cricket();

c2.playerName = "Rohit Sharma";
c2.playerNumber = 2;
c2.team = "MI";
c2.role = "Batsman";
c2.matches = 240;
c2.runs = 10500;
c2.wickets = 8;
c2.strikeRate = 135.4;
c2.average = 48.2;
c2.centuries = 31;
c2.halfCenturies = 55;
c2.catches = 95;
c2.runOuts = 14;
c2.country = "India";
c2.age = 36;
c2.battingStyle = "Right Hand";
c2.bowlingStyle = "Right Arm Off Spin";
c2.jerseyNumber = 45;
c2.stadium = "Wankhede";
c2.ranking = 2;

System.out.println(c2.playerName);
System.out.println(c2.playerNumber);
System.out.println(c2.team);
System.out.println(c2.role);
System.out.println(c2.matches);
System.out.println(c2.runs);
System.out.println(c2.wickets);
System.out.println(c2.strikeRate);
System.out.println(c2.average);
System.out.println(c2.centuries);
System.out.println(c2.halfCenturies);
System.out.println(c2.catches);
System.out.println(c2.runOuts);
System.out.println(c2.country);
System.out.println(c2.age);
System.out.println(c2.battingStyle);
System.out.println(c2.bowlingStyle);
System.out.println(c2.jerseyNumber);
System.out.println(c2.stadium);
System.out.println(c2.ranking);

Cricket c3 = new Cricket();

c3.playerName = "KL Rahul";
c3.playerNumber = 3;
c3.team = "LSG";
c3.role = "Batsman";
c3.matches = 150;
c3.runs = 6500;
c3.wickets = 0;
c3.strikeRate = 132.4;
c3.average = 45.6;
c3.centuries = 12;
c3.halfCenturies = 40;
c3.catches = 60;
c3.runOuts = 10;
c3.country = "India";
c3.age = 32;
c3.battingStyle = "Right Hand";
c3.bowlingStyle = "None";
c3.jerseyNumber = 1;
c3.stadium = "Lucknow";
c3.ranking = 5;

System.out.println(c3.playerName);
System.out.println(c3.playerNumber);
System.out.println(c3.team);
System.out.println(c3.role);
System.out.println(c3.matches);
System.out.println(c3.runs);
System.out.println(c3.wickets);
System.out.println(c3.strikeRate);
System.out.println(c3.average);
System.out.println(c3.centuries);
System.out.println(c3.halfCenturies);
System.out.println(c3.catches);
System.out.println(c3.runOuts);
System.out.println(c3.country);
System.out.println(c3.age);
System.out.println(c3.battingStyle);
System.out.println(c3.bowlingStyle);
System.out.println(c3.jerseyNumber);
System.out.println(c3.stadium);
System.out.println(c3.ranking);

Cricket c4 = new Cricket();

c4.playerName = "Hardik Pandya";
c4.playerNumber = 4;
c4.team = "GT";
c4.role = "All Rounder";
c4.matches = 120;
c4.runs = 4000;
c4.wickets = 80;
c4.strikeRate = 140.3;
c4.average = 35.2;
c4.centuries = 3;
c4.halfCenturies = 20;
c4.catches = 50;
c4.runOuts = 8;
c4.country = "India";
c4.age = 31;
c4.battingStyle = "Right Hand";
c4.bowlingStyle = "Right Arm Fast";
c4.jerseyNumber = 33;
c4.stadium = "Ahmedabad";
c4.ranking = 8;

System.out.println(c4.playerName);
System.out.println(c4.playerNumber);
System.out.println(c4.team);
System.out.println(c4.role);
System.out.println(c4.matches);
System.out.println(c4.runs);
System.out.println(c4.wickets);
System.out.println(c4.strikeRate);
System.out.println(c4.average);
System.out.println(c4.centuries);
System.out.println(c4.halfCenturies);
System.out.println(c4.catches);
System.out.println(c4.runOuts);
System.out.println(c4.country);
System.out.println(c4.age);
System.out.println(c4.battingStyle);
System.out.println(c4.bowlingStyle);
System.out.println(c4.jerseyNumber);
System.out.println(c4.stadium);
System.out.println(c4.ranking); 

Cricket c5 = new Cricket();

c5.playerName = "Jasprit Bumrah";
c5.playerNumber = 5;
c5.team = "MI";
c5.role = "Bowler";
c5.matches = 160;
c5.runs = 350;
c5.wickets = 210;
c5.strikeRate = 85.4;
c5.average = 22.3;
c5.centuries = 0;
c5.halfCenturies = 0;
c5.catches = 30;
c5.runOuts = 5;
c5.country = "India";
c5.age = 31;
c5.battingStyle = "Right Hand";
c5.bowlingStyle = "Right Arm Fast";
c5.jerseyNumber = 93;
c5.stadium = "Wankhede";
c5.ranking = 1;

System.out.println(c5.playerName);
System.out.println(c5.playerNumber);
System.out.println(c5.team);
System.out.println(c5.role);
System.out.println(c5.matches);
System.out.println(c5.runs);
System.out.println(c5.wickets);
System.out.println(c5.strikeRate);
System.out.println(c5.average);
System.out.println(c5.centuries);
System.out.println(c5.halfCenturies);
System.out.println(c5.catches);
System.out.println(c5.runOuts);
System.out.println(c5.country);
System.out.println(c5.age);
System.out.println(c5.battingStyle);
System.out.println(c5.bowlingStyle);
System.out.println(c5.jerseyNumber);
System.out.println(c5.stadium);
System.out.println(c5.ranking);

Cricket c6 = new Cricket();
c6.playerName = "Shreyas Iyer";
c6.playerNumber = 6;
c6.team = "DC";
c6.role = "Batsman";
c6.matches = 120;
c6.runs = 4500;
c6.wickets = 5;
c6.strikeRate = 130.2;
c6.average = 40.5;
c6.centuries = 8;
c6.halfCenturies = 25;
c6.catches = 40;
c6.runOuts = 6;
c6.country = "India";
c6.age = 29;
c6.battingStyle = "Right Hand";
c6.bowlingStyle = "None";
c6.jerseyNumber = 12;
c6.stadium = "Feroz Shah Kotla";
c6.ranking = 10;

System.out.println(c6.playerName);
System.out.println(c6.playerNumber);
System.out.println(c6.team);
System.out.println(c6.role);
System.out.println(c6.matches);
System.out.println(c6.runs);
System.out.println(c6.wickets);
System.out.println(c6.strikeRate);
System.out.println(c6.average);
System.out.println(c6.centuries);
System.out.println(c6.halfCenturies);
System.out.println(c6.catches);
System.out.println(c6.runOuts);
System.out.println(c6.country);
System.out.println(c6.age);
System.out.println(c6.battingStyle);
System.out.println(c6.bowlingStyle);
System.out.println(c6.jerseyNumber);
System.out.println(c6.stadium);
System.out.println(c6.ranking);

Cricket c7 = new Cricket();
c7.playerName = "Rishabh Pant";
c7.playerNumber = 7;
c7.team = "DC";
c7.role = "WicketKeeper Batsman";
c7.matches = 100;
c7.runs = 3500;
c7.wickets = 2;
c7.strikeRate = 140.0;
c7.average = 38.0;
c7.centuries = 6;
c7.halfCenturies = 18;
c7.catches = 45;
c7.runOuts = 8;
c7.country = "India";
c7.age = 25;
c7.battingStyle = "Left Hand";
c7.bowlingStyle = "None";
c7.jerseyNumber = 17;
c7.stadium = "Feroz Shah Kotla";
c7.ranking = 9;

System.out.println(c7.playerName);
System.out.println(c7.playerNumber);
System.out.println(c7.team);
System.out.println(c7.role);
System.out.println(c7.matches);
System.out.println(c7.runs);
System.out.println(c7.wickets);
System.out.println(c7.strikeRate);
System.out.println(c7.average);
System.out.println(c7.centuries);
System.out.println(c7.halfCenturies);
System.out.println(c7.catches);
System.out.println(c7.runOuts);
System.out.println(c7.country);
System.out.println(c7.age);
System.out.println(c7.battingStyle);
System.out.println(c7.bowlingStyle);
System.out.println(c7.jerseyNumber);
System.out.println(c7.stadium);
System.out.println(c7.ranking);

Cricket c8 = new Cricket();
c8.playerName = "Bhuvneshwar Kumar";
c8.playerNumber = 8;
c8.team = "SRH";
c8.role = "Bowler";
c8.matches = 140;
c8.runs = 300;
c8.wickets = 180;
c8.strikeRate = 85.0;
c8.average = 24.0;
c8.centuries = 0;
c8.halfCenturies = 0;
c8.catches = 35;
c8.runOuts = 5;
c8.country = "India";
c8.age = 32;
c8.battingStyle = "Right Hand";
c8.bowlingStyle = "Right Arm Medium";
c8.jerseyNumber = 15;
c8.stadium = "Hyderabad";
c8.ranking = 6;

System.out.println(c8.playerName);
System.out.println(c8.playerNumber);
System.out.println(c8.team);
System.out.println(c8.role);
System.out.println(c8.matches);
System.out.println(c8.runs);
System.out.println(c8.wickets);
System.out.println(c8.strikeRate);
System.out.println(c8.average);
System.out.println(c8.centuries);
System.out.println(c8.halfCenturies);
System.out.println(c8.catches);
System.out.println(c8.runOuts);
System.out.println(c8.country);
System.out.println(c8.age);
System.out.println(c8.battingStyle);
System.out.println(c8.bowlingStyle);
System.out.println(c8.jerseyNumber);
System.out.println(c8.stadium);
System.out.println(c8.ranking);

Cricket c9 = new Cricket();
c9.playerName = "Jadeja";
c9.playerNumber = 9;
c9.team = "CSK";
c9.role = "All Rounder";
c9.matches = 180;
c9.runs = 3500;
c9.wickets = 120;
c9.strikeRate = 125.0;
c9.average = 32.0;
c9.centuries = 1;
c9.halfCenturies = 20;
c9.catches = 80;
c9.runOuts = 10;
c9.country = "India";
c9.age = 34;
c9.battingStyle = "Left Hand";
c9.bowlingStyle = "Left Arm Spin";
c9.jerseyNumber = 8;
c9.stadium = "Chepauk";
c9.ranking = 7;

System.out.println(c9.playerName);
System.out.println(c9.playerNumber);
System.out.println(c9.team);
System.out.println(c9.role);
System.out.println(c9.matches);
System.out.println(c9.runs);
System.out.println(c9.wickets);
System.out.println(c9.strikeRate);
System.out.println(c9.average);
System.out.println(c9.centuries);
System.out.println(c9.halfCenturies);
System.out.println(c9.catches);
System.out.println(c9.runOuts);
System.out.println(c9.country);
System.out.println(c9.age);
System.out.println(c9.battingStyle);
System.out.println(c9.bowlingStyle);
System.out.println(c9.jerseyNumber);
System.out.println(c9.stadium);
System.out.println(c9.ranking);

Cricket c10 = new Cricket();
c10.playerName = "Ravindra Jadeja";
c10.playerNumber = 10;
c10.team = "CSK";
c10.role = "All Rounder";
c10.matches = 190;
c10.runs = 3700;
c10.wickets = 130;
c10.strikeRate = 127.0;
c10.average = 33.0;
c10.centuries = 1;
c10.halfCenturies = 21;
c10.catches = 85;
c10.runOuts = 11;
c10.country = "India";
c10.age = 34;
c10.battingStyle = "Left Hand";
c10.bowlingStyle = "Left Arm Spin";
c10.jerseyNumber = 8;
c10.stadium = "Chepauk";
c10.ranking = 7;

System.out.println(c10.playerName);
System.out.println(c10.playerNumber);
System.out.println(c10.team);
System.out.println(c10.role);
System.out.println(c10.matches);
System.out.println(c10.runs);
System.out.println(c10.wickets);
System.out.println(c10.strikeRate);
System.out.println(c10.average);
System.out.println(c10.centuries);
System.out.println(c10.halfCenturies);
System.out.println(c10.catches);
System.out.println(c10.runOuts);
System.out.println(c10.country);
System.out.println(c10.age);
System.out.println(c10.battingStyle);
System.out.println(c10.bowlingStyle);
System.out.println(c10.jerseyNumber);
System.out.println(c10.stadium);
System.out.println(c10.ranking);

Cricket c11 = new Cricket();
c11.playerName = "Shubman Gill";
c11.playerNumber = 11;
c11.team = "GT";
c11.role = "Batsman";
c11.matches = 110;
c11.runs = 4000;
c11.wickets = 2;
c11.strikeRate = 132.0;
c11.average = 41.0;
c11.centuries = 6;
c11.halfCenturies = 18;
c11.catches = 40;
c11.runOuts = 5;
c11.country = "India";
c11.age = 24;
c11.battingStyle = "Right Hand";
c11.bowlingStyle = "None";
c11.jerseyNumber = 2;
c11.stadium = "Ahmedabad";
c11.ranking = 11;

System.out.println(c11.playerName);
System.out.println(c11.playerNumber);
System.out.println(c11.team);
System.out.println(c11.role);
System.out.println(c11.matches);
System.out.println(c11.runs);
System.out.println(c11.wickets);
System.out.println(c11.strikeRate);
System.out.println(c11.average);
System.out.println(c11.centuries);
System.out.println(c11.halfCenturies);
System.out.println(c11.catches);
System.out.println(c11.runOuts);
System.out.println(c11.country);
System.out.println(c11.age);
System.out.println(c11.battingStyle);
System.out.println(c11.bowlingStyle);
System.out.println(c11.jerseyNumber);
System.out.println(c11.stadium);
System.out.println(c11.ranking);

Cricket c12 = new Cricket();
c12.playerName = "Ishant Sharma";
c12.playerNumber = 12;
c12.team = "DC";
c12.role = "Bowler";
c12.matches = 130;
c12.runs = 150;
c12.wickets = 160;
c12.strikeRate = 80.0;
c12.average = 25.0;
c12.centuries = 0;
c12.halfCenturies = 0;
c12.catches = 25;
c12.runOuts = 3;
c12.country = "India";
c12.age = 34;
c12.battingStyle = "Right Hand";
c12.bowlingStyle = "Right Arm Fast";
c12.jerseyNumber = 14;
c12.stadium = "Delhi";
c12.ranking = 12;

System.out.println(c12.playerName);
System.out.println(c12.playerNumber);
System.out.println(c12.team);
System.out.println(c12.role);
System.out.println(c12.matches);
System.out.println(c12.runs);
System.out.println(c12.wickets);
System.out.println(c12.strikeRate);
System.out.println(c12.average);
System.out.println(c12.centuries);
System.out.println(c12.halfCenturies);
System.out.println(c12.catches);
System.out.println(c12.runOuts);
System.out.println(c12.country);
System.out.println(c12.age);
System.out.println(c12.battingStyle);
System.out.println(c12.bowlingStyle);
System.out.println(c12.jerseyNumber);
System.out.println(c12.stadium);
System.out.println(c12.ranking);

Cricket c13 = new Cricket();
c13.playerName = "Ravichandran Ashwin";
c13.playerNumber = 13;
c13.team = "RR";
c13.role = "All Rounder";
c13.matches = 170;
c13.runs = 3300;
c13.wickets = 150;
c13.strikeRate = 120.5;
c13.average = 32.0;
c13.centuries = 1;
c13.halfCenturies = 15;
c13.catches = 70;
c13.runOuts = 7;
c13.country = "India";
c13.age = 35;
c13.battingStyle = "Right Hand";
c13.bowlingStyle = "Right Arm Off Spin";
c13.jerseyNumber = 21;
c13.stadium = "Jaipur";
c13.ranking = 8;

System.out.println(c13.playerName);
System.out.println(c13.playerNumber);
System.out.println(c13.team);
System.out.println(c13.role);
System.out.println(c13.matches);
System.out.println(c13.runs);
System.out.println(c13.wickets);
System.out.println(c13.strikeRate);
System.out.println(c13.average);
System.out.println(c13.centuries);
System.out.println(c13.halfCenturies);
System.out.println(c13.catches);
System.out.println(c13.runOuts);
System.out.println(c13.country);
System.out.println(c13.age);
System.out.println(c13.battingStyle);
System.out.println(c13.bowlingStyle);
System.out.println(c13.jerseyNumber);
System.out.println(c13.stadium);
System.out.println(c13.ranking);

Cricket c14 = new Cricket();
c14.playerName = "Mohammed Shami";
c14.playerNumber = 14;
c14.team = "GT";
c14.role = "Bowler";
c14.matches = 140;
c14.runs = 200;
c14.wickets = 170;
c14.strikeRate = 82.0;
c14.average = 23.0;
c14.centuries = 0;
c14.halfCenturies = 0;
c14.catches = 30;
c14.runOuts = 4;
c14.country = "India";
c14.age = 33;
c14.battingStyle = "Right Hand";
c14.bowlingStyle = "Right Arm Fast";
c14.jerseyNumber = 11;
c14.stadium = "Ahmedabad";
c14.ranking = 9;

System.out.println(c14.playerName);
System.out.println(c14.playerNumber);
System.out.println(c14.team);
System.out.println(c14.role);
System.out.println(c14.matches);
System.out.println(c14.runs);
System.out.println(c14.wickets);
System.out.println(c14.strikeRate);
System.out.println(c14.average);
System.out.println(c14.centuries);
System.out.println(c14.halfCenturies);
System.out.println(c14.catches);
System.out.println(c14.runOuts);
System.out.println(c14.country);
System.out.println(c14.age);
System.out.println(c14.battingStyle);
System.out.println(c14.bowlingStyle);
System.out.println(c14.jerseyNumber);
System.out.println(c14.stadium);
System.out.println(c14.ranking);

Cricket c15 = new Cricket();
c15.playerName = "Prithvi Shaw";
c15.playerNumber = 15;
c15.team = "DC";
c15.role = "Batsman";
c15.matches = 90;
c15.runs = 3200;
c15.wickets = 0;
c15.strikeRate = 138.0;
c15.average = 42.0;
c15.centuries = 4;
c15.halfCenturies = 16;
c15.catches = 35;
c15.runOuts = 5;
c15.country = "India";
c15.age = 23;
c15.battingStyle = "Right Hand";
c15.bowlingStyle = "None";
c15.jerseyNumber = 4;
c15.stadium = "Delhi";
c15.ranking = 12;

System.out.println(c15.playerName);
System.out.println(c15.playerNumber);
System.out.println(c15.team);
System.out.println(c15.role);
System.out.println(c15.matches);
System.out.println(c15.runs);
System.out.println(c15.wickets);
System.out.println(c15.strikeRate);
System.out.println(c15.average);
System.out.println(c15.centuries);
System.out.println(c15.halfCenturies);
System.out.println(c15.catches);
System.out.println(c15.runOuts);
System.out.println(c15.country);
System.out.println(c15.age);
System.out.println(c15.battingStyle);
System.out.println(c15.bowlingStyle);
System.out.println(c15.jerseyNumber);
System.out.println(c15.stadium);
System.out.println(c15.ranking);

Cricket c16 = new Cricket();
c16.playerName = "Shivam Dube";
c16.playerNumber = 16;
c16.team = "RCB";
c16.role = "All Rounder";
c16.matches = 80;
c16.runs = 1500;
c16.wickets = 40;
c16.strikeRate = 135.0;
c16.average = 32.0;
c16.centuries = 1;
c16.halfCenturies = 8;
c16.catches = 20;
c16.runOuts = 3;
c16.country = "India";
c16.age = 27;
c16.battingStyle = "Right Hand";
c16.bowlingStyle = "Right Arm Medium";
c16.jerseyNumber = 20;
c16.stadium = "M Chinnaswamy";
c16.ranking = 14;

System.out.println(c16.playerName);
System.out.println(c16.playerNumber);
System.out.println(c16.team);
System.out.println(c16.role);
System.out.println(c16.matches);
System.out.println(c16.runs);
System.out.println(c16.wickets);
System.out.println(c16.strikeRate);
System.out.println(c16.average);
System.out.println(c16.centuries);
System.out.println(c16.halfCenturies);
System.out.println(c16.catches);
System.out.println(c16.runOuts);
System.out.println(c16.country);
System.out.println(c16.age);
System.out.println(c16.battingStyle);
System.out.println(c16.bowlingStyle);
System.out.println(c16.jerseyNumber);
System.out.println(c16.stadium);
System.out.println(c16.ranking);

Cricket c17 = new Cricket();
c17.playerName = "Washington Sundar";
c17.playerNumber = 17;
c17.team = "RCB";
c17.role = "All Rounder";
c17.matches = 100;
c17.runs = 1200;
c17.wickets = 50;
c17.strikeRate = 128.0;
c17.average = 30.0;
c17.centuries = 0;
c17.halfCenturies = 6;
c17.catches = 25;
c17.runOuts = 4;
c17.country = "India";
c17.age = 25;
c17.battingStyle = "Left Hand";
c17.bowlingStyle = "Off Spin";
c17.jerseyNumber = 12;
c17.stadium = "M Chinnaswamy";
c17.ranking = 15;

System.out.println(c17.playerName);
System.out.println(c17.playerNumber);
System.out.println(c17.team);
System.out.println(c17.role);
System.out.println(c17.matches);
System.out.println(c17.runs);
System.out.println(c17.wickets);
System.out.println(c17.strikeRate);
System.out.println(c17.average);
System.out.println(c17.centuries);
System.out.println(c17.halfCenturies);
System.out.println(c17.catches);
System.out.println(c17.runOuts);
System.out.println(c17.country);
System.out.println(c17.age);
System.out.println(c17.battingStyle);
System.out.println(c17.bowlingStyle);
System.out.println(c17.jerseyNumber);
System.out.println(c17.stadium);
System.out.println(c17.ranking);

Cricket c18 = new Cricket();
c18.playerName = "Deepak Chahar";
c18.playerNumber = 18;
c18.team = "CSK";
c18.role = "Bowler";
c18.matches = 90;
c18.runs = 150;
c18.wickets = 110;
c18.strikeRate = 80.0;
c18.average = 24.0;
c18.centuries = 0;
c18.halfCenturies = 0;
c18.catches = 30;
c18.runOuts = 4;
c18.country = "India";
c18.age = 28;
c18.battingStyle = "Right Hand";
c18.bowlingStyle = "Right Arm Medium";
c18.jerseyNumber = 23;
c18.stadium = "Chepauk";
c18.ranking = 16;

System.out.println(c18.playerName);
System.out.println(c18.playerNumber);
System.out.println(c18.team);
System.out.println(c18.role);
System.out.println(c18.matches);
System.out.println(c18.runs);
System.out.println(c18.wickets);
System.out.println(c18.strikeRate);
System.out.println(c18.average);
System.out.println(c18.centuries);
System.out.println(c18.halfCenturies);
System.out.println(c18.catches);
System.out.println(c18.runOuts);
System.out.println(c18.country);
System.out.println(c18.age);
System.out.println(c18.battingStyle);
System.out.println(c18.bowlingStyle);
System.out.println(c18.jerseyNumber);
System.out.println(c18.stadium);
System.out.println(c18.ranking);

Cricket c19 = new Cricket();
c19.playerName = "Rahul Tewatia";
c19.playerNumber = 19;
c19.team = "RR";
c19.role = "All Rounder";
c19.matches = 70;
c19.runs = 1400;
c19.wickets = 35;
c19.strikeRate = 135.0;
c19.average = 31.0;
c19.centuries = 0;
c19.halfCenturies = 5;
c19.catches = 18;
c19.runOuts = 2;
c19.country = "India";
c19.age = 29;
c19.battingStyle = "Right Hand";
c19.bowlingStyle = "Medium Pace";
c19.jerseyNumber = 16;
c19.stadium = "Jaipur";
c19.ranking = 17;

System.out.println(c19.playerName);
System.out.println(c19.playerNumber);
System.out.println(c19.team);
System.out.println(c19.role);
System.out.println(c19.matches);
System.out.println(c19.runs);
System.out.println(c19.wickets);
System.out.println(c19.strikeRate);
System.out.println(c19.average);
System.out.println(c19.centuries);
System.out.println(c19.halfCenturies);
System.out.println(c19.catches);
System.out.println(c19.runOuts);
System.out.println(c19.country);
System.out.println(c19.age);
System.out.println(c19.battingStyle);
System.out.println(c19.bowlingStyle);
System.out.println(c19.jerseyNumber);
System.out.println(c19.stadium);
System.out.println(c19.ranking);

Cricket c20 = new Cricket();
c20.playerName = "Sam Curran";
c20.playerNumber = 20;
c20.team = "KKR";
c20.role = "All Rounder";
c20.matches = 85;
c20.runs = 1600;
c20.wickets = 50;
c20.strikeRate = 130.0;
c20.average = 32.0;
c20.centuries = 0;
c20.halfCenturies = 7;
c20.catches = 22;
c20.runOuts = 3;
c20.country = "India";
c20.age = 24;
c20.battingStyle = "Left Hand";
c20.bowlingStyle = "Left Arm Medium";
c20.jerseyNumber = 10;
c20.stadium = "Kolkata";
c20.ranking = 18;

System.out.println(c20.playerName);
System.out.println(c20.playerNumber);
System.out.println(c20.team);
System.out.println(c20.role);
System.out.println(c20.matches);
System.out.println(c20.runs);
System.out.println(c20.wickets);
System.out.println(c20.strikeRate);
System.out.println(c20.average);
System.out.println(c20.centuries);
System.out.println(c20.halfCenturies);
System.out.println(c20.catches);
System.out.println(c20.runOuts);
System.out.println(c20.country);
System.out.println(c20.age);
System.out.println(c20.battingStyle);
System.out.println(c20.bowlingStyle);
System.out.println(c20.jerseyNumber);
System.out.println(c20.stadium);
System.out.println(c20.ranking);

Cricket c21 = new Cricket();
c21.playerName = "Shivam Sharma";
c21.playerNumber = 21;
c21.team = "MI";
c21.role = "Batsman";
c21.matches = 60;
c21.runs = 1300;
c21.wickets = 0;
c21.strikeRate = 128.0;
c21.average = 30.0;
c21.centuries = 1;
c21.halfCenturies = 7;
c21.catches = 15;
c21.runOuts = 2;
c21.country = "India";
c21.age = 26;
c21.battingStyle = "Right Hand";
c21.bowlingStyle = "None";
c21.jerseyNumber = 19;
c21.stadium = "Wankhede";
c21.ranking = 19;

System.out.println(c21.playerName);
System.out.println(c21.playerNumber);
System.out.println(c21.team);
System.out.println(c21.role);
System.out.println(c21.matches);
System.out.println(c21.runs);
System.out.println(c21.wickets);
System.out.println(c21.strikeRate);
System.out.println(c21.average);
System.out.println(c21.centuries);
System.out.println(c21.halfCenturies);
System.out.println(c21.catches);
System.out.println(c21.runOuts);
System.out.println(c21.country);
System.out.println(c21.age);
System.out.println(c21.battingStyle);
System.out.println(c21.bowlingStyle);
System.out.println(c21.jerseyNumber);
System.out.println(c21.stadium);
System.out.println(c21.ranking);

Cricket c22 = new Cricket();
c22.playerName = "Devdutt Padikkal";
c22.playerNumber = 22;
c22.team = "RCB";
c22.role = "Batsman";
c22.matches = 75;
c22.runs = 1450;
c22.wickets = 0;
c22.strikeRate = 132.0;
c22.average = 33.0;
c22.centuries = 2;
c22.halfCenturies = 10;
c22.catches = 20;
c22.runOuts = 3;
c22.country = "India";
c22.age = 23;
c22.battingStyle = "Right Hand";
c22.bowlingStyle = "None";
c22.jerseyNumber = 16;
c22.stadium = "M Chinnaswamy";
c22.ranking = 20;

System.out.println(c22.playerName);
System.out.println(c22.playerNumber);
System.out.println(c22.team);
System.out.println(c22.role);
System.out.println(c22.matches);
System.out.println(c22.runs);
System.out.println(c22.wickets);
System.out.println(c22.strikeRate);
System.out.println(c22.average);
System.out.println(c22.centuries);
System.out.println(c22.halfCenturies);
System.out.println(c22.catches);
System.out.println(c22.runOuts);
System.out.println(c22.country);
System.out.println(c22.age);
System.out.println(c22.battingStyle);
System.out.println(c22.bowlingStyle);
System.out.println(c22.jerseyNumber);
System.out.println(c22.stadium);
System.out.println(c22.ranking);

Cricket c23 = new Cricket();
c23.playerName = "Ruturaj Gaikwad";
c23.playerNumber = 23;
c23.team = "CSK";
c23.role = "Batsman";
c23.matches = 85;
c23.runs = 1600;
c23.wickets = 0;
c23.strikeRate = 134.0;
c23.average = 34.0;
c23.centuries = 3;
c23.halfCenturies = 12;
c23.catches = 25;
c23.runOuts = 3;
c23.country = "India";
c23.age = 26;
c23.battingStyle = "Right Hand";
c23.bowlingStyle = "None";
c23.jerseyNumber = 7;
c23.stadium = "Chepauk";
c23.ranking = 21;

System.out.println(c23.playerName);
System.out.println(c23.playerNumber);
System.out.println(c23.team);
System.out.println(c23.role);
System.out.println(c23.matches);
System.out.println(c23.runs);
System.out.println(c23.wickets);
System.out.println(c23.strikeRate);
System.out.println(c23.average);
System.out.println(c23.centuries);
System.out.println(c23.halfCenturies);
System.out.println(c23.catches);
System.out.println(c23.runOuts);
System.out.println(c23.country);
System.out.println(c23.age);
System.out.println(c23.battingStyle);
System.out.println(c23.bowlingStyle);
System.out.println(c23.jerseyNumber);
System.out.println(c23.stadium);
System.out.println(c23.ranking);

Cricket c24 = new Cricket();
c24.playerName = "David Warner";
c24.playerNumber = 24;
c24.team = "SRH";
c24.role = "Batsman";
c24.matches = 120;
c24.runs = 4500;
c24.wickets = 0;
c24.strikeRate = 140.0;
c24.average = 42.0;
c24.centuries = 10;
c24.halfCenturies = 25;
c24.catches = 50;
c24.runOuts = 6;
c24.country = "Australia";
c24.age = 35;
c24.battingStyle = "Left Hand";
c24.bowlingStyle = "None";
c24.jerseyNumber = 31;
c24.stadium = "Hyderabad";
c24.ranking = 22;

System.out.println(c24.playerName);
System.out.println(c24.playerNumber);
System.out.println(c24.team);
System.out.println(c24.role);
System.out.println(c24.matches);
System.out.println(c24.runs);
System.out.println(c24.wickets);
System.out.println(c24.strikeRate);
System.out.println(c24.average);
System.out.println(c24.centuries);
System.out.println(c24.halfCenturies);
System.out.println(c24.catches);
System.out.println(c24.runOuts);
System.out.println(c24.country);
System.out.println(c24.age);
System.out.println(c24.battingStyle);
System.out.println(c24.bowlingStyle);
System.out.println(c24.jerseyNumber);
System.out.println(c24.stadium);
System.out.println(c24.ranking);

Cricket c25 = new Cricket();
c25.playerName = "Kane Williamson";
c25.playerNumber = 25;
c25.team = "SRH";
c25.role = "Batsman";
c25.matches = 100;
c25.runs = 4200;
c25.wickets = 0;
c25.strikeRate = 132.0;
c25.average = 41.0;
c25.centuries = 9;
c25.halfCenturies = 20;
c25.catches = 45;
c25.runOuts = 5;
c25.country = "New Zealand";
c25.age = 31;
c25.battingStyle = "Right Hand";
c25.bowlingStyle = "None";
c25.jerseyNumber = 22;
c25.stadium = "Hyderabad";
c25.ranking = 23;

System.out.println(c25.playerName);
System.out.println(c25.playerNumber);
System.out.println(c25.team);
System.out.println(c25.role);
System.out.println(c25.matches);
System.out.println(c25.runs);
System.out.println(c25.wickets);
System.out.println(c25.strikeRate);
System.out.println(c25.average);
System.out.println(c25.centuries);
System.out.println(c25.halfCenturies);
System.out.println(c25.catches);
System.out.println(c25.runOuts);
System.out.println(c25.country);
System.out.println(c25.age);
System.out.println(c25.battingStyle);
System.out.println(c25.bowlingStyle);
System.out.println(c25.jerseyNumber);
System.out.println(c25.stadium);
System.out.println(c25.ranking);


Cricket c26 = new Cricket("MS Dhoni", 26, "CSK", "WicketKeeper", 350, 17000, 1, 135.0, 50.2, 48, 96, 250, 40, "India", 41, "Right Hand", "Right Arm Medium", 7, "Chepauk", 1);

System.out.println(c26.playerName);
System.out.println(c26.playerNumber);
System.out.println(c26.team);
System.out.println(c26.role);
System.out.println(c26.matches);
System.out.println(c26.runs);
System.out.println(c26.wickets);
System.out.println(c26.strikeRate);
System.out.println(c26.average);
System.out.println(c26.centuries);
System.out.println(c26.halfCenturies);
System.out.println(c26.catches);
System.out.println(c26.runOuts);
System.out.println(c26.country);
System.out.println(c26.age);
System.out.println(c26.battingStyle);
System.out.println(c26.bowlingStyle);
System.out.println(c26.jerseyNumber);
System.out.println(c26.stadium);
System.out.println(c26.ranking);

Cricket c27 = new Cricket("Ravindra Jadeja", 27, "CSK", "All Rounder", 190, 3700, 130, 127.0, 33.0, 1, 21, 85, 11, "India", 34, "Left Hand", "Left Arm Spin", 8, "Chepauk", 7);

System.out.println(c27.playerName);
System.out.println(c27.playerNumber);
System.out.println(c27.team);
System.out.println(c27.role);
System.out.println(c27.matches);
System.out.println(c27.runs);
System.out.println(c27.wickets);
System.out.println(c27.strikeRate);
System.out.println(c27.average);
System.out.println(c27.centuries);
System.out.println(c27.halfCenturies);
System.out.println(c27.catches);
System.out.println(c27.runOuts);
System.out.println(c27.country);
System.out.println(c27.age);
System.out.println(c27.battingStyle);
System.out.println(c27.bowlingStyle);
System.out.println(c27.jerseyNumber);
System.out.println(c27.stadium);
System.out.println(c27.ranking);

Cricket c28 = new Cricket("Shubman Gill", 28, "GT", "Batsman", 110, 4000, 2, 132.0, 41.0, 6, 18, 40, 5, "India", 24, "Right Hand", "None", 2, "Ahmedabad", 11);

System.out.println(c28.playerName);
System.out.println(c28.playerNumber);
System.out.println(c28.team);
System.out.println(c28.role);
System.out.println(c28.matches);
System.out.println(c28.runs);
System.out.println(c28.wickets);
System.out.println(c28.strikeRate);
System.out.println(c28.average);
System.out.println(c28.centuries);
System.out.println(c28.halfCenturies);
System.out.println(c28.catches);
System.out.println(c28.runOuts);
System.out.println(c28.country);
System.out.println(c28.age);
System.out.println(c28.battingStyle);
System.out.println(c28.bowlingStyle);
System.out.println(c28.jerseyNumber);
System.out.println(c28.stadium);
System.out.println(c28.ranking);

Cricket c29 = new Cricket("Ishant Sharma", 29, "DC", "Bowler", 130, 150, 160, 80.0, 25.0, 0, 0, 25, 3, "India", 34, "Right Hand", "Right Arm Fast", 14, "Delhi", 12);

System.out.println(c29.playerName);
System.out.println(c29.playerNumber);
System.out.println(c29.team);
System.out.println(c29.role);
System.out.println(c29.matches);
System.out.println(c29.runs);
System.out.println(c29.wickets);
System.out.println(c29.strikeRate);
System.out.println(c29.average);
System.out.println(c29.centuries);
System.out.println(c29.halfCenturies);
System.out.println(c29.catches);
System.out.println(c29.runOuts);
System.out.println(c29.country);
System.out.println(c29.age);
System.out.println(c29.battingStyle);
System.out.println(c29.bowlingStyle);
System.out.println(c29.jerseyNumber);
System.out.println(c29.stadium);
System.out.println(c29.ranking);

Cricket c30 = new Cricket("Ravichandran Ashwin", 30, "RR", "All Rounder", 170, 3300, 150, 120.5, 32.0, 1, 15, 70, 7, "India", 35, "Right Hand", "Right Arm Off Spin", 21, "Jaipur", 8);

System.out.println(c30.playerName);
System.out.println(c30.playerNumber);
System.out.println(c30.team);
System.out.println(c30.role);
System.out.println(c30.matches);
System.out.println(c30.runs);
System.out.println(c30.wickets);
System.out.println(c30.strikeRate);
System.out.println(c30.average);
System.out.println(c30.centuries);
System.out.println(c30.halfCenturies);
System.out.println(c30.catches);
System.out.println(c30.runOuts);
System.out.println(c30.country);
System.out.println(c30.age);
System.out.println(c30.battingStyle);
System.out.println(c30.bowlingStyle);
System.out.println(c30.jerseyNumber);
System.out.println(c30.stadium);
System.out.println(c30.ranking);

Cricket c31 = new Cricket("Glenn Maxwell", 31, "RCB", "All Rounder", 85, 2100, 45, 140.0, 32.5, 1, 10, 28, 3, "Australia", 33, "Right Hand", "Right Arm Off Spin", 32, "M Chinnaswamy", 9);
System.out.println(c31.playerName); System.out.println(c31.playerNumber); System.out.println(c31.team); System.out.println(c31.role); System.out.println(c31.matches); System.out.println(c31.runs); System.out.println(c31.wickets); System.out.println(c31.strikeRate); System.out.println(c31.average); System.out.println(c31.centuries); System.out.println(c31.halfCenturies); System.out.println(c31.catches); System.out.println(c31.runOuts); System.out.println(c31.country); System.out.println(c31.age); System.out.println(c31.battingStyle); System.out.println(c31.bowlingStyle); System.out.println(c31.jerseyNumber); System.out.println(c31.stadium); System.out.println(c31.ranking);

Cricket c32 = new Cricket("Travis Head", 32, "SRH", "Batsman", 90, 2300, 5, 138.0, 34.0, 2, 15, 25, 4, "Australia", 30, "Right Hand", "None", 7, "Hyderabad", 10);
System.out.println(c32.playerName); System.out.println(c32.playerNumber); System.out.println(c32.team); System.out.println(c32.role); System.out.println(c32.matches); System.out.println(c32.runs); System.out.println(c32.wickets); System.out.println(c32.strikeRate); System.out.println(c32.average); System.out.println(c32.centuries); System.out.println(c32.halfCenturies); System.out.println(c32.catches); System.out.println(c32.runOuts); System.out.println(c32.country); System.out.println(c32.age); System.out.println(c32.battingStyle); System.out.println(c32.bowlingStyle); System.out.println(c32.jerseyNumber); System.out.println(c32.stadium); System.out.println(c32.ranking);

Cricket c33 = new Cricket("Ben Stokes", 33, "RR", "All Rounder", 100, 2800, 80, 136.0, 36.0, 3, 18, 30, 5, "England", 32, "Left Hand", "Right Arm Fast", 55, "Jaipur", 5);
System.out.println(c33.playerName); System.out.println(c33.playerNumber); System.out.println(c33.team); System.out.println(c33.role); System.out.println(c33.matches); System.out.println(c33.runs); System.out.println(c33.wickets); System.out.println(c33.strikeRate); System.out.println(c33.average); System.out.println(c33.centuries); System.out.println(c33.halfCenturies); System.out.println(c33.catches); System.out.println(c33.runOuts); System.out.println(c33.country); System.out.println(c33.age); System.out.println(c33.battingStyle); System.out.println(c33.bowlingStyle); System.out.println(c33.jerseyNumber); System.out.println(c33.stadium); System.out.println(c33.ranking);

Cricket c34 = new Cricket("Jos Buttler", 34, "RR", "Batsman", 95, 3000, 0, 140.5, 38.0, 5, 20, 27, 2, "England", 31, "Right Hand", "None", 63, "Jaipur", 6);
System.out.println(c34.playerName); System.out.println(c34.playerNumber); System.out.println(c34.team); System.out.println(c34.role); System.out.println(c34.matches); System.out.println(c34.runs); System.out.println(c34.wickets); System.out.println(c34.strikeRate); System.out.println(c34.average); System.out.println(c34.centuries); System.out.println(c34.halfCenturies); System.out.println(c34.catches); System.out.println(c34.runOuts); System.out.println(c34.country); System.out.println(c34.age); System.out.println(c34.battingStyle); System.out.println(c34.bowlingStyle); System.out.println(c34.jerseyNumber); System.out.println(c34.stadium); System.out.println(c34.ranking);

Cricket c35 = new Cricket("Hardik Pandya", 35, "MI", "All Rounder", 110, 2500, 90, 138.5, 34.5, 1, 15, 30, 4, "India", 29, "Right Hand", "Right Arm Medium", 33, "Wankhede", 7);
System.out.println(c35.playerName); System.out.println(c35.playerNumber); System.out.println(c35.team); System.out.println(c35.role); System.out.println(c35.matches); System.out.println(c35.runs); System.out.println(c35.wickets); System.out.println(c35.strikeRate); System.out.println(c35.average); System.out.println(c35.centuries); System.out.println(c35.halfCenturies); System.out.println(c35.catches); System.out.println(c35.runOuts); System.out.println(c35.country); System.out.println(c35.age); System.out.println(c35.battingStyle); System.out.println(c35.bowlingStyle); System.out.println(c35.jerseyNumber); System.out.println(c35.stadium); System.out.println(c35.ranking);

Cricket c36 = new Cricket("Shreyas Iyer", 36, "KKR", "Batsman", 105, 2700, 0, 137.0, 36.0, 4, 18, 28, 3, "India", 28, "Right Hand", "None", 7, "Kolkata", 8);
System.out.println(c36.playerName); System.out.println(c36.playerNumber); System.out.println(c36.team); System.out.println(c36.role); System.out.println(c36.matches); System.out.println(c36.runs); System.out.println(c36.wickets); System.out.println(c36.strikeRate); System.out.println(c36.average); System.out.println(c36.centuries); System.out.println(c36.halfCenturies); System.out.println(c36.catches); System.out.println(c36.runOuts); System.out.println(c36.country); System.out.println(c36.age); System.out.println(c36.battingStyle); System.out.println(c36.bowlingStyle); System.out.println(c36.jerseyNumber); System.out.println(c36.stadium); System.out.println(c36.ranking);

Cricket c37 = new Cricket("Pat Cummins", 37, "KKR", "Bowler", 95, 200, 130, 85.0, 25.0, 0, 0, 20, 3, "Australia", 28, "Right Hand", "Right Arm Fast", 30, "Kolkata", 9);
System.out.println(c37.playerName); System.out.println(c37.playerNumber); System.out.println(c37.team); System.out.println(c37.role); System.out.println(c37.matches); System.out.println(c37.runs); System.out.println(c37.wickets); System.out.println(c37.strikeRate); System.out.println(c37.average); System.out.println(c37.centuries); System.out.println(c37.halfCenturies); System.out.println(c37.catches); System.out.println(c37.runOuts); System.out.println(c37.country); System.out.println(c37.age); System.out.println(c37.battingStyle); System.out.println(c37.bowlingStyle); System.out.println(c37.jerseyNumber); System.out.println(c37.stadium); System.out.println(c37.ranking);

Cricket c38 = new Cricket("David Willey", 38, "DC", "All Rounder", 80, 1500, 50, 130.0, 30.0, 0, 6, 15, 2, "England", 30, "Left Hand", "Left Arm Medium", 11, "Delhi", 11);
System.out.println(c38.playerName); System.out.println(c38.playerNumber); System.out.println(c38.team); System.out.println(c38.role); System.out.println(c38.matches); System.out.println(c38.runs); System.out.println(c38.wickets); System.out.println(c38.strikeRate); System.out.println(c38.average); System.out.println(c38.centuries); System.out.println(c38.halfCenturies); System.out.println(c38.catches); System.out.println(c38.runOuts); System.out.println(c38.country); System.out.println(c38.age); System.out.println(c38.battingStyle); System.out.println(c38.bowlingStyle); System.out.println(c38.jerseyNumber); System.out.println(c38.stadium); System.out.println(c38.ranking);

Cricket c39 = new Cricket("Shakib Al Hasan", 39, "DC", "All Rounder", 120, 4000, 150, 125.0, 33.0, 2, 25, 50, 5, "Bangladesh", 35, "Left Hand", "Left Arm Spin", 75, "Delhi", 6);
System.out.println(c39.playerName); System.out.println(c39.playerNumber); System.out.println(c39.team); System.out.println(c39.role); System.out.println(c39.matches); System.out.println(c39.runs); System.out.println(c39.wickets); System.out.println(c39.strikeRate); System.out.println(c39.average); System.out.println(c39.centuries); System.out.println(c39.halfCenturies); System.out.println(c39.catches); System.out.println(c39.runOuts); System.out.println(c39.country); System.out.println(c39.age); System.out.println(c39.battingStyle); System.out.println(c39.bowlingStyle); System.out.println(c39.jerseyNumber); System.out.println(c39.stadium); System.out.println(c39.ranking);

Cricket c40 = new Cricket("Chris Gayle", 40, "RCB", "Batsman", 150, 5500, 0, 145.0, 42.0, 12, 30, 60, 6, "West Indies", 42, "Left Hand", "None", 45, "M Chinnaswamy", 3);
System.out.println(c40.playerName); System.out.println(c40.playerNumber); System.out.println(c40.team); System.out.println(c40.role); System.out.println(c40.matches); System.out.println(c40.runs); System.out.println(c40.wickets); System.out.println(c40.strikeRate); System.out.println(c40.average); System.out.println(c40.centuries); System.out.println(c40.halfCenturies); System.out.println(c40.catches); System.out.println(c40.runOuts); System.out.println(c40.country); System.out.println(c40.age); System.out.println(c40.battingStyle); System.out.println(c40.bowlingStyle); System.out.println(c40.jerseyNumber); System.out.println(c40.stadium); System.out.println(c40.ranking);

Cricket c41 = new Cricket("KL Rahul", 41, "PBKS", "Batsman", 140, 4800, 0, 138.0, 40.0, 8, 28, 50, 5, "India", 31, "Right Hand", "None", 1, "Mohali", 4);
System.out.println(c41.playerName); System.out.println(c41.playerNumber); System.out.println(c41.team); System.out.println(c41.role); System.out.println(c41.matches); System.out.println(c41.runs); System.out.println(c41.wickets); System.out.println(c41.strikeRate); System.out.println(c41.average); System.out.println(c41.centuries); System.out.println(c41.halfCenturies); System.out.println(c41.catches); System.out.println(c41.runOuts); System.out.println(c41.country); System.out.println(c41.age); System.out.println(c41.battingStyle); System.out.println(c41.bowlingStyle); System.out.println(c41.jerseyNumber); System.out.println(c41.stadium); System.out.println(c41.ranking);

Cricket c42 = new Cricket("Hardik Pandya", 42, "MI", "All Rounder", 110, 2500, 90, 138.5, 34.5, 1, 15, 30, 4, "India", 29, "Right Hand", "Right Arm Medium", 33, "Wankhede", 7);
System.out.println(c42.playerName); System.out.println(c42.playerNumber); System.out.println(c42.team); System.out.println(c42.role); System.out.println(c42.matches); System.out.println(c42.runs); System.out.println(c42.wickets); System.out.println(c42.strikeRate); System.out.println(c42.average); System.out.println(c42.centuries); System.out.println(c42.halfCenturies); System.out.println(c42.catches); System.out.println(c42.runOuts); System.out.println(c42.country); System.out.println(c42.age); System.out.println(c42.battingStyle); System.out.println(c42.bowlingStyle); System.out.println(c42.jerseyNumber); System.out.println(c42.stadium); System.out.println(c42.ranking);

Cricket c43 = new Cricket("Shreyas Iyer", 43, "KKR", "Batsman", 105, 2700, 0, 137.0, 36.0, 4, 18, 28, 3, "India", 28, "Right Hand", "None", 7, "Kolkata", 8);
System.out.println(c43.playerName); System.out.println(c43.playerNumber); System.out.println(c43.team); System.out.println(c43.role); System.out.println(c43.matches); System.out.println(c43.runs); System.out.println(c43.wickets); System.out.println(c43.strikeRate); System.out.println(c43.average); System.out.println(c43.centuries); System.out.println(c43.halfCenturies); System.out.println(c43.catches); System.out.println(c43.runOuts); System.out.println(c43.country); System.out.println(c43.age); System.out.println(c43.battingStyle); System.out.println(c43.bowlingStyle); System.out.println(c43.jerseyNumber); System.out.println(c43.stadium); System.out.println(c43.ranking);

Cricket c44 = new Cricket("Pat Cummins", 44, "KKR", "Bowler", 95, 200, 130, 85.0, 25.0, 0, 0, 20, 3, "Australia", 28, "Right Hand", "Right Arm Fast", 30, "Kolkata", 9);
System.out.println(c44.playerName); System.out.println(c44.playerNumber); System.out.println(c44.team); System.out.println(c44.role); System.out.println(c44.matches); System.out.println(c44.runs); System.out.println(c44.wickets); System.out.println(c44.strikeRate); System.out.println(c44.average); System.out.println(c44.centuries); System.out.println(c44.halfCenturies); System.out.println(c44.catches); System.out.println(c44.runOuts); System.out.println(c44.country); System.out.println(c44.age); System.out.println(c44.battingStyle); System.out.println(c44.bowlingStyle); System.out.println(c44.jerseyNumber); System.out.println(c44.stadium); System.out.println(c44.ranking);

Cricket c45 = new Cricket("David Willey", 45, "DC", "All Rounder", 80, 1500, 50, 130.0, 30.0, 0, 6, 15, 2, "England", 30, "Left Hand", "Left Arm Medium", 11, "Delhi", 11);
System.out.println(c45.playerName); System.out.println(c45.playerNumber); System.out.println(c45.team); System.out.println(c45.role); System.out.println(c45.matches); System.out.println(c45.runs); System.out.println(c45.wickets); System.out.println(c45.strikeRate); System.out.println(c45.average); System.out.println(c45.centuries); System.out.println(c45.halfCenturies); System.out.println(c45.catches); System.out.println(c45.runOuts); System.out.println(c45.country); System.out.println(c45.age); System.out.println(c45.battingStyle); System.out.println(c45.bowlingStyle); System.out.println(c45.jerseyNumber); System.out.println(c45.stadium); System.out.println(c45.ranking);

Cricket c46 = new Cricket("Shakib Al Hasan", 46, "DC", "All Rounder", 120, 4000, 150, 125.0, 33.0, 2, 25, 50, 5, "Bangladesh", 35, "Left Hand", "Left Arm Spin", 75, "Delhi", 6);
System.out.println(c46.playerName); System.out.println(c46.playerNumber); System.out.println(c46.team); System.out.println(c46.role); System.out.println(c46.matches); System.out.println(c46.runs); System.out.println(c46.wickets); System.out.println(c46.strikeRate); System.out.println(c46.average); System.out.println(c46.centuries); System.out.println(c46.halfCenturies); System.out.println(c46.catches); System.out.println(c46.runOuts); System.out.println(c46.country); System.out.println(c46.age); System.out.println(c46.battingStyle); System.out.println(c46.bowlingStyle); System.out.println(c46.jerseyNumber); System.out.println(c46.stadium); System.out.println(c46.ranking);

Cricket c47 = new Cricket("Chris Gayle", 47, "RCB", "Batsman", 150, 5500, 0, 145.0, 42.0, 12, 30, 60, 6, "West Indies", 42, "Left Hand", "None", 45, "M Chinnaswamy", 3);
System.out.println(c47.playerName); System.out.println(c47.playerNumber); System.out.println(c47.team); System.out.println(c47.role); System.out.println(c47.matches); System.out.println(c47.runs); System.out.println(c47.wickets); System.out.println(c47.strikeRate); System.out.println(c47.average); System.out.println(c47.centuries); System.out.println(c47.halfCenturies); System.out.println(c47.catches); System.out.println(c47.runOuts); System.out.println(c47.country); System.out.println(c47.age); System.out.println(c47.battingStyle); System.out.println(c47.bowlingStyle); System.out.println(c47.jerseyNumber); System.out.println(c47.stadium); System.out.println(c47.ranking);

Cricket c48 = new Cricket("KL Rahul", 48, "PBKS", "Batsman", 140, 4800, 0, 138.0, 40.0, 8, 28, 50, 5, "India", 31, "Right Hand", "None", 1, "Mohali", 4);
System.out.println(c48.playerName); System.out.println(c48.playerNumber); System.out.println(c48.team); System.out.println(c48.role); System.out.println(c48.matches); System.out.println(c48.runs); System.out.println(c48.wickets); System.out.println(c48.strikeRate); System.out.println(c48.average); System.out.println(c48.centuries); System.out.println(c48.halfCenturies); System.out.println(c48.catches); System.out.println(c48.runOuts); System.out.println(c48.country); System.out.println(c48.age); System.out.println(c48.battingStyle); System.out.println(c48.bowlingStyle); System.out.println(c48.jerseyNumber); System.out.println(c48.stadium); System.out.println(c48.ranking);

Cricket c49 = new Cricket("Aaron Finch", 49, "RR", "Batsman", 100, 4000, 0, 140.0, 39.0, 5, 20, 30, 3, "Australia", 34, "Right Hand", "None", 17, "Jaipur", 12);
System.out.println(c49.playerName); System.out.println(c49.playerNumber); System.out.println(c49.team); System.out.println(c49.role); System.out.println(c49.matches); System.out.println(c49.runs); System.out.println(c49.wickets); System.out.println(c49.strikeRate); System.out.println(c49.average); System.out.println(c49.centuries); System.out.println(c49.halfCenturies); System.out.println(c49.catches); System.out.println(c49.runOuts); System.out.println(c49.country); System.out.println(c49.age); System.out.println(c49.battingStyle); System.out.println(c49.bowlingStyle); System.out.println(c49.jerseyNumber); System.out.println(c49.stadium); System.out.println(c49.ranking);

Cricket c50 = new Cricket("Steve Smith", 50, "RR", "Batsman", 120, 4500, 0, 135.0, 41.0, 6, 22, 35, 4, "Australia", 33, "Right Hand", "None", 49, "Jaipur", 13);
System.out.println(c50.playerName); System.out.println(c50.playerNumber); System.out.println(c50.team); System.out.println(c50.role); System.out.println(c50.matches); System.out.println(c50.runs); System.out.println(c50.wickets); System.out.println(c50.strikeRate); System.out.println(c50.average); System.out.println(c50.centuries); System.out.println(c50.halfCenturies); System.out.println(c50.catches); System.out.println(c50.runOuts); System.out.println(c50.country); System.out.println(c50.age); System.out.println(c50.battingStyle); System.out.println(c50.bowlingStyle); System.out.println(c50.jerseyNumber); System.out.println(c50.stadium); System.out.println(c50.ranking);

}

}