class RacketExecutor {

public static void main(String[] args)  {

Racket r1 = new Racket();
r1.brand = "Yonex";
r1.type = "Badminton";
r1.weight = 88.0;
r1.length = 675.0;
r1.material = "Carbon Fiber";
r1.gripType = "Standard";
r1.price = 5000;
r1.color = "Blue";
r1.playerUsed = "PV Sindhu";
r1.rating = 9;

System.out.println(r1.brand);
System.out.println(r1.type);
System.out.println(r1.weight);
System.out.println(r1.length);
System.out.println(r1.material);
System.out.println(r1.gripType);
System.out.println(r1.price);
System.out.println(r1.color);
System.out.println(r1.playerUsed);
System.out.println(r1.rating);


Racket r2 = new Racket();
r2.brand = "Li-Ning";
r2.type = "Badminton";
r2.weight = 85.0;
r2.length = 680.0;
r2.material = "Graphite";
r2.gripType = "Pro Grip";
r2.price = 6000;
r2.color = "Red";
r2.playerUsed = "Kidambi Srikanth";
r2.rating = 8;

System.out.println(r2.brand);
System.out.println(r2.type);
System.out.println(r2.weight);
System.out.println(r2.length);
System.out.println(r2.material);
System.out.println(r2.gripType);
System.out.println(r2.price);
System.out.println(r2.color);
System.out.println(r2.playerUsed);
System.out.println(r2.rating);

Racket r3 = new Racket();
r3.brand = "Babolat";
r3.type = "Tennis";
r3.weight = 300.0;
r3.length = 685.0;
r3.material = "Aluminum";
r3.gripType = "Standard";
r3.price = 8000;
r3.color = "Black";
r3.playerUsed = "Roger Federer";
r3.rating = 9;

System.out.println(r3.brand);
System.out.println(r3.type);
System.out.println(r3.weight);
System.out.println(r3.length);
System.out.println(r3.material);
System.out.println(r3.gripType);
System.out.println(r3.price);
System.out.println(r3.color);
System.out.println(r3.playerUsed);
System.out.println(r3.rating);

Racket r4 = new Racket();
r4.brand = "Yonex";
r4.type = "Badminton";
r4.weight = 90.0;
r4.length = 670.0;
r4.material = "Carbon Fiber";
r4.gripType = "Standard";
r4.price = 5200;
r4.color = "Green";
r4.playerUsed = "Carolina Marin";
r4.rating = 9;

System.out.println(r4.brand);
System.out.println(r4.type);
System.out.println(r4.weight);
System.out.println(r4.length);
System.out.println(r4.material);
System.out.println(r4.gripType);
System.out.println(r4.price);
System.out.println(r4.color);
System.out.println(r4.playerUsed);
System.out.println(r4.rating);

Racket r5 = new Racket();
r5.brand = "Head";
r5.type = "Tennis";
r5.weight = 295.0;
r5.length = 680.0;
r5.material = "Graphite";
r5.gripType = "Pro Grip";
r5.price = 7500;
r5.color = "Blue";
r5.playerUsed = "Rafael Nadal";
r5.rating = 10;

System.out.println(r5.brand);
System.out.println(r5.type);
System.out.println(r5.weight);
System.out.println(r5.length);
System.out.println(r5.material);
System.out.println(r5.gripType);
System.out.println(r5.price);
System.out.println(r5.color);
System.out.println(r5.playerUsed);
System.out.println(r5.rating);

Racket r6 = new Racket();
r6.brand = "Yonex";
r6.type = "Badminton";
r6.weight = 87.0;
r6.length = 675.0;
r6.material = "Carbon Fiber";
r6.gripType = "Standard";
r6.price = 5100;
r6.color = "Yellow";
r6.playerUsed = "Saina Nehwal";
r6.rating = 8;

System.out.println(r6.brand);
System.out.println(r6.type);
System.out.println(r6.weight);
System.out.println(r6.length);
System.out.println(r6.material);
System.out.println(r6.gripType);
System.out.println(r6.price);
System.out.println(r6.color);
System.out.println(r6.playerUsed);
System.out.println(r6.rating);

Racket r7 = new Racket();
r7.brand = "Li-Ning";
r7.type = "Badminton";
r7.weight = 86.0;
r7.length = 680.0;
r7.material = "Graphite";
r7.gripType = "Pro Grip";
r7.price = 6000;
r7.color = "Orange";
r7.playerUsed = "HS Prannoy";
r7.rating = 9;

System.out.println(r7.brand);
System.out.println(r7.type);
System.out.println(r7.weight);
System.out.println(r7.length);
System.out.println(r7.material);
System.out.println(r7.gripType);
System.out.println(r7.price);
System.out.println(r7.color);
System.out.println(r7.playerUsed);
System.out.println(r7.rating);

Racket r8 = new Racket();
r8.brand = "Babolat";
r8.type = "Tennis";
r8.weight = 298.0;
r8.length = 685.0;
r8.material = "Aluminum";
r8.gripType = "Standard";
r8.price = 8000;
r8.color = "Red";
r8.playerUsed = "Novak Djokovic";
r8.rating = 10;

System.out.println(r8.brand);
System.out.println(r8.type);
System.out.println(r8.weight);
System.out.println(r8.length);
System.out.println(r8.material);
System.out.println(r8.gripType);
System.out.println(r8.price);
System.out.println(r8.color);
System.out.println(r8.playerUsed);
System.out.println(r8.rating);

Racket r9 = new Racket();
r9.brand = "Yonex";
r9.type = "Badminton";
r9.weight = 88.0;
r9.length = 678.0;
r9.material = "Carbon Fiber";
r9.gripType = "Standard";
r9.price = 5200;
r9.color = "Pink";
r9.playerUsed = "Viktor Axelsen";
r9.rating = 9;

System.out.println(r9.brand);
System.out.println(r9.type);
System.out.println(r9.weight);
System.out.println(r9.length);
System.out.println(r9.material);
System.out.println(r9.gripType);
System.out.println(r9.price);
System.out.println(r9.color);
System.out.println(r9.playerUsed);
System.out.println(r9.rating);

Racket r10 = new Racket();
r10.brand = "Head";
r10.type = "Tennis";
r10.weight = 300.0;
r10.length = 690.0;
r10.material = "Graphite";
r10.gripType = "Pro Grip";
r10.price = 7500;
r10.color = "White";
r10.playerUsed = "Andy Murray";
r10.rating = 9;

System.out.println(r10.brand);
System.out.println(r10.type);
System.out.println(r10.weight);
System.out.println(r10.length);
System.out.println(r10.material);
System.out.println(r10.gripType);
System.out.println(r10.price);
System.out.println(r10.color);
System.out.println(r10.playerUsed);
System.out.println(r10.rating);

 Racket r11 = new Racket();
r11.brand = "Yonex";
r11.type = "Badminton";
r11.weight = 89.0;
r11.length = 677.0;
r11.material = "Carbon Fiber";
r11.gripType = "Standard";
r11.price = 5300;
r11.color = "Purple";
r11.playerUsed = "Lee Chong Wei";
r11.rating = 8;

System.out.println(r11.brand);
System.out.println(r11.type);
System.out.println(r11.weight);
System.out.println(r11.length);
System.out.println(r11.material);
System.out.println(r11.gripType);
System.out.println(r11.price);
System.out.println(r11.color);
System.out.println(r11.playerUsed);
System.out.println(r11.rating);

Racket r12 = new Racket();
r12.brand = "Li-Ning";
r12.type = "Badminton";
r12.weight = 86.5;
r12.length = 681.0;
r12.material = "Graphite";
r12.gripType = "Pro Grip";
r12.price = 6100;
r12.color = "Orange";
r12.playerUsed = "Viktor Axelsen";
r12.rating = 9;

System.out.println(r12.brand);
System.out.println(r12.type);
System.out.println(r12.weight);
System.out.println(r12.length);
System.out.println(r12.material);
System.out.println(r12.gripType);
System.out.println(r12.price);
System.out.println(r12.color);
System.out.println(r12.playerUsed);
System.out.println(r12.rating);

Racket r13 = new Racket();
r13.brand = "Babolat";
r13.type = "Tennis";
r13.weight = 299.0;
r13.length = 686.0;
r13.material = "Aluminum";
r13.gripType = "Standard";
r13.price = 8050;
r13.color = "Black";
r13.playerUsed = "Serena Williams";
r13.rating = 10;

System.out.println(r13.brand);
System.out.println(r13.type);
System.out.println(r13.weight);
System.out.println(r13.length);
System.out.println(r13.material);
System.out.println(r13.gripType);
System.out.println(r13.price);
System.out.println(r13.color);
System.out.println(r13.playerUsed);
System.out.println(r13.rating);

Racket r14 = new Racket();
r14.brand = "Yonex";
r14.type = "Badminton";
r14.weight = 87.5;
r14.length = 679.0;
r14.material = "Carbon Fiber";
r14.gripType = "Standard";
r14.price = 5400;
r14.color = "Blue";
r14.playerUsed = "Carolina Marin";
r14.rating = 9;

System.out.println(r14.brand);
System.out.println(r14.type);
System.out.println(r14.weight);
System.out.println(r14.length);
System.out.println(r14.material);
System.out.println(r14.gripType);
System.out.println(r14.price);
System.out.println(r14.color);
System.out.println(r14.playerUsed);
System.out.println(r14.rating);

Racket r15 = new Racket();
r15.brand = "Head";
r15.type = "Tennis";
r15.weight = 296.0;
r15.length = 681.0;
r15.material = "Graphite";
r15.gripType = "Pro Grip";
r15.price = 7600;
r15.color = "White";
r15.playerUsed = "Andy Murray";
r15.rating = 9;

System.out.println(r15.brand);
System.out.println(r15.type);
System.out.println(r15.weight);
System.out.println(r15.length);
System.out.println(r15.material);
System.out.println(r15.gripType);
System.out.println(r15.price);
System.out.println(r15.color);
System.out.println(r15.playerUsed);
System.out.println(r15.rating);

Racket r16 = new Racket();
r16.brand = "Yonex";
r16.type = "Badminton";
r16.weight = 88.5;
r16.length = 678.0;
r16.material = "Carbon Fiber";
r16.gripType = "Standard";
r16.price = 5500;
r16.color = "Red";
r16.playerUsed = "PV Sindhu";
r16.rating = 8;

System.out.println(r16.brand);
System.out.println(r16.type);
System.out.println(r16.weight);
System.out.println(r16.length);
System.out.println(r16.material);
System.out.println(r16.gripType);
System.out.println(r16.price);
System.out.println(r16.color);
System.out.println(r16.playerUsed);
System.out.println(r16.rating);

Racket r17 = new Racket();
r17.brand = "Li-Ning";
r17.type = "Badminton";
r17.weight = 85.5;
r17.length = 682.0;
r17.material = "Graphite";
r17.gripType = "Pro Grip";
r17.price = 6200;
r17.color = "Yellow";
r17.playerUsed = "Kidambi Srikanth";
r17.rating = 9;

System.out.println(r17.brand);
System.out.println(r17.type);
System.out.println(r17.weight);
System.out.println(r17.length);
System.out.println(r17.material);
System.out.println(r17.gripType);
System.out.println(r17.price);
System.out.println(r17.color);
System.out.println(r17.playerUsed);
System.out.println(r17.rating);

Racket r18 = new Racket();
r18.brand = "Babolat";
r18.type = "Tennis";
r18.weight = 301.0;
r18.length = 687.0;
r18.material = "Aluminum";
r18.gripType = "Standard";
r18.price = 8100;
r18.color = "Black";
r18.playerUsed = "Roger Federer";
r18.rating = 10;

System.out.println(r18.brand);
System.out.println(r18.type);
System.out.println(r18.weight);
System.out.println(r18.length);
System.out.println(r18.material);
System.out.println(r18.gripType);
System.out.println(r18.price);
System.out.println(r18.color);
System.out.println(r18.playerUsed);
System.out.println(r18.rating);

Racket r19 = new Racket();
r19.brand = "Yonex";
r19.type = "Badminton";
r19.weight = 87.0;
r19.length = 680.0;
r19.material = "Carbon Fiber";
r19.gripType = "Standard";
r19.price = 5600;
r19.color = "Green";
r19.playerUsed = "Carolina Marin";
r19.rating = 9;

System.out.println(r19.brand);
System.out.println(r19.type);
System.out.println(r19.weight);
System.out.println(r19.length);
System.out.println(r19.material);
System.out.println(r19.gripType);
System.out.println(r19.price);
System.out.println(r19.color);
System.out.println(r19.playerUsed);
System.out.println(r19.rating);

Racket r20 = new Racket();
r20.brand = "Head";
r20.type = "Tennis";
r20.weight = 297.0;
r20.length = 682.0;
r20.material = "Graphite";
r20.gripType = "Pro Grip";
r20.price = 7700;
r20.color = "White";
r20.playerUsed = "Rafael Nadal";
r20.rating = 10;

System.out.println(r20.brand);
System.out.println(r20.type);
System.out.println(r20.weight);
System.out.println(r20.length);
System.out.println(r20.material);
System.out.println(r20.gripType);
System.out.println(r20.price);
System.out.println(r20.color);
System.out.println(r20.playerUsed);
System.out.println(r20.rating);

Racket r21 = new Racket();
r21.brand = "Yonex";
r21.type = "Badminton";
r21.weight = 88.0;
r21.length = 679.0;
r21.material = "Carbon Fiber";
r21.gripType = "Standard";
r21.price = 5700;
r21.color = "Blue";
r21.playerUsed = "PV Sindhu";
r21.rating = 9;

System.out.println(r21.brand);
System.out.println(r21.type);
System.out.println(r21.weight);
System.out.println(r21.length);
System.out.println(r21.material);
System.out.println(r21.gripType);
System.out.println(r21.price);
System.out.println(r21.color);
System.out.println(r21.playerUsed);
System.out.println(r21.rating);

Racket r22 = new Racket();
r22.brand = "Li-Ning";
r22.type = "Badminton";
r22.weight = 86.0;
r22.length = 681.0;
r22.material = "Graphite";
r22.gripType = "Pro Grip";
r22.price = 6300;
r22.color = "Red";
r22.playerUsed = "Kidambi Srikanth";
r22.rating = 9;

System.out.println(r22.brand);
System.out.println(r22.type);
System.out.println(r22.weight);
System.out.println(r22.length);
System.out.println(r22.material);
System.out.println(r22.gripType);
System.out.println(r22.price);
System.out.println(r22.color);
System.out.println(r22.playerUsed);
System.out.println(r22.rating);

Racket r23 = new Racket();
r23.brand = "Babolat";
r23.type = "Tennis";
r23.weight = 300.0;
r23.length = 685.0;
r23.material = "Aluminum";
r23.gripType = "Standard";
r23.price = 8150;
r23.color = "Black";
r23.playerUsed = "Serena Williams";
r23.rating = 10;

System.out.println(r23.brand);
System.out.println(r23.type);
System.out.println(r23.weight);
System.out.println(r23.length);
System.out.println(r23.material);
System.out.println(r23.gripType);
System.out.println(r23.price);
System.out.println(r23.color);
System.out.println(r23.playerUsed);
System.out.println(r23.rating);

Racket r24 = new Racket();
r24.brand = "Yonex";
r24.type = "Badminton";
r24.weight = 89.0;
r24.length = 682.0;
r24.material = "Carbon Fiber";
r24.gripType = "Standard";
r24.price = 5800;
r24.color = "Yellow";
r24.playerUsed = "Carolina Marin";
r24.rating = 9;

System.out.println(r24.brand);
System.out.println(r24.type);
System.out.println(r24.weight);
System.out.println(r24.length);
System.out.println(r24.material);
System.out.println(r24.gripType);
System.out.println(r24.price);
System.out.println(r24.color);
System.out.println(r24.playerUsed);
System.out.println(r24.rating);

Racket r25 = new Racket();
r25.brand = "Head";
r25.type = "Tennis";
r25.weight = 298.0;
r25.length = 688.0;
r25.material = "Graphite";
r25.gripType = "Pro Grip";
r25.price = 7800;
r25.color = "White";
r25.playerUsed = "Andy Murray";
r25.rating = 10;

System.out.println(r25.brand);
System.out.println(r25.type);
System.out.println(r25.weight);
System.out.println(r25.length);
System.out.println(r25.material);
System.out.println(r25.gripType);
System.out.println(r25.price);
System.out.println(r25.color);
System.out.println(r25.playerUsed);
System.out.println(r25.rating);

Racket r26 = new Racket("Yonex", "Badminton", 88.0, 675.0, "Carbon Fiber", "Standard", 5000, "Blue", "PV Sindhu", 9);
System.out.println(r26.brand);
System.out.println(r26.type);
System.out.println(r26.weight);
System.out.println(r26.length);
System.out.println(r26.material);
System.out.println(r26.gripType);
System.out.println(r26.price);
System.out.println(r26.color);
System.out.println(r26.playerUsed);
System.out.println(r26.rating);

Racket r27 = new Racket("Li-Ning", "Badminton", 85.0, 680.0, "Graphite", "Pro Grip", 6000, "Red", "Kidambi Srikanth", 8);
System.out.println(r27.brand);
System.out.println(r27.type);
System.out.println(r27.weight);
System.out.println(r27.length);
System.out.println(r27.material);
System.out.println(r27.gripType);
System.out.println(r27.price);
System.out.println(r27.color);
System.out.println(r27.playerUsed);
System.out.println(r27.rating);

Racket r28 = new Racket("Babolat", "Tennis", 300.0, 685.0, "Aluminum", "Standard", 8000, "Black", "Roger Federer", 9);
System.out.println(r28.brand);
System.out.println(r28.type);
System.out.println(r28.weight);
System.out.println(r28.length);
System.out.println(r28.material);
System.out.println(r28.gripType);
System.out.println(r28.price);
System.out.println(r28.color);
System.out.println(r28.playerUsed);
System.out.println(r28.rating);

Racket r29 = new Racket("Head", "Tennis", 295.0, 680.0, "Graphite", "Pro Grip", 7500, "Blue", "Rafael Nadal", 10);
System.out.println(r29.brand);
System.out.println(r29.type);
System.out.println(r29.weight);
System.out.println(r29.length);
System.out.println(r29.material);
System.out.println(r29.gripType);
System.out.println(r29.price);
System.out.println(r29.color);
System.out.println(r29.playerUsed);
System.out.println(r29.rating);

Racket r30 = new Racket("Yonex", "Badminton", 90.0, 670.0, "Carbon Fiber", "Standard", 5200, "Green", "Carolina Marin", 9);
System.out.println(r30.brand);
System.out.println(r30.type);
System.out.println(r30.weight);
System.out.println(r30.length);
System.out.println(r30.material);
System.out.println(r30.gripType);
System.out.println(r30.price);
System.out.println(r30.color);
System.out.println(r30.playerUsed);
System.out.println(r30.rating);

Racket r31 = new Racket("Li-Ning", "Badminton", 87.0, 678.0, "Graphite", "Pro Grip", 6100, "Yellow", "HS Prannoy", 8);
System.out.println(r31.brand);
System.out.println(r31.type);
System.out.println(r31.weight);
System.out.println(r31.length);
System.out.println(r31.material);
System.out.println(r31.gripType);
System.out.println(r31.price);
System.out.println(r31.color);
System.out.println(r31.playerUsed);
System.out.println(r31.rating);

Racket r32 = new Racket("Babolat", "Tennis", 298.0, 686.0, "Aluminum", "Standard", 8050, "Black", "Serena Williams", 10);
System.out.println(r32.brand);
System.out.println(r32.type);
System.out.println(r32.weight);
System.out.println(r32.length);
System.out.println(r32.material);
System.out.println(r32.gripType);
System.out.println(r32.price);
System.out.println(r32.color);
System.out.println(r32.playerUsed);
System.out.println(r32.rating);

Racket r33 = new Racket("Yonex", "Badminton", 89.0, 679.0, "Carbon Fiber", "Standard", 5400, "Purple", "Lee Chong Wei", 9);
System.out.println(r33.brand);
System.out.println(r33.type);
System.out.println(r33.weight);
System.out.println(r33.length);
System.out.println(r33.material);
System.out.println(r33.gripType);
System.out.println(r33.price);
System.out.println(r33.color);
System.out.println(r33.playerUsed);
System.out.println(r33.rating);

Racket r34 = new Racket("Head", "Tennis", 297.0, 682.0, "Graphite", "Pro Grip", 7700, "White", "Andy Murray", 10);
System.out.println(r34.brand);
System.out.println(r34.type);
System.out.println(r34.weight);
System.out.println(r34.length);
System.out.println(r34.material);
System.out.println(r34.gripType);
System.out.println(r34.price);
System.out.println(r34.color);
System.out.println(r34.playerUsed);
System.out.println(r34.rating);

Racket r35 = new Racket("Li-Ning", "Badminton", 86.0, 681.0, "Graphite", "Pro Grip", 6200, "Orange", "Viktor Axelsen", 9);
System.out.println(r35.brand);
System.out.println(r35.type);
System.out.println(r35.weight);
System.out.println(r35.length);
System.out.println(r35.material);
System.out.println(r35.gripType);
System.out.println(r35.price);
System.out.println(r35.color);
System.out.println(r35.playerUsed);
System.out.println(r35.rating);

Racket r36 = new Racket("Yonex", "Badminton", 88.5, 677.0, "Carbon Fiber", "Standard", 5500, "Red", "PV Sindhu", 9);
System.out.println(r36.brand);
System.out.println(r36.type);
System.out.println(r36.weight);
System.out.println(r36.length);
System.out.println(r36.material);
System.out.println(r36.gripType);
System.out.println(r36.price);
System.out.println(r36.color);
System.out.println(r36.playerUsed);
System.out.println(r36.rating);

Racket r37 = new Racket("Li-Ning", "Badminton", 85.5, 680.0, "Graphite", "Pro Grip", 6300, "Blue", "Kidambi Srikanth", 8);
System.out.println(r37.brand);
System.out.println(r37.type);
System.out.println(r37.weight);
System.out.println(r37.length);
System.out.println(r37.material);
System.out.println(r37.gripType);
System.out.println(r37.price);
System.out.println(r37.color);
System.out.println(r37.playerUsed);
System.out.println(r37.rating);

Racket r38 = new Racket("Babolat", "Tennis", 299.0, 686.0, "Aluminum", "Standard", 8100, "Black", "Roger Federer", 10);
System.out.println(r38.brand);
System.out.println(r38.type);
System.out.println(r38.weight);
System.out.println(r38.length);
System.out.println(r38.material);
System.out.println(r38.gripType);
System.out.println(r38.price);
System.out.println(r38.color);
System.out.println(r38.playerUsed);
System.out.println(r38.rating);

Racket r39 = new Racket("Head", "Tennis", 296.0, 683.0, "Graphite", "Pro Grip", 7800, "White", "Rafael Nadal", 10);
System.out.println(r39.brand);
System.out.println(r39.type);
System.out.println(r39.weight);
System.out.println(r39.length);
System.out.println(r39.material);
System.out.println(r39.gripType);
System.out.println(r39.price);
System.out.println(r39.color);
System.out.println(r39.playerUsed);
System.out.println(r39.rating);

Racket r40 = new Racket("Yonex", "Badminton", 87.0, 679.0, "Carbon Fiber", "Standard", 5600, "Green", "Carolina Marin", 9);
System.out.println(r40.brand);
System.out.println(r40.type);
System.out.println(r40.weight);
System.out.println(r40.length);
System.out.println(r40.material);
System.out.println(r40.gripType);
System.out.println(r40.price);
System.out.println(r40.color);
System.out.println(r40.playerUsed);
System.out.println(r40.rating);

Racket r41 = new Racket("Li-Ning", "Badminton", 86.0, 682.0, "Graphite", "Pro Grip", 6400, "Orange", "HS Prannoy", 9);
System.out.println(r41.brand);
System.out.println(r41.type);
System.out.println(r41.weight);
System.out.println(r41.length);
System.out.println(r41.material);
System.out.println(r41.gripType);
System.out.println(r41.price);
System.out.println(r41.color);
System.out.println(r41.playerUsed);
System.out.println(r41.rating);

Racket r42 = new Racket("Babolat", "Tennis", 301.0, 687.0, "Aluminum", "Standard", 8200, "Black", "Serena Williams", 10);
System.out.println(r42.brand);
System.out.println(r42.type);
System.out.println(r42.weight);
System.out.println(r42.length);
System.out.println(r42.material);
System.out.println(r42.gripType);
System.out.println(r42.price);
System.out.println(r42.color);
System.out.println(r42.playerUsed);
System.out.println(r42.rating);

Racket r43 = new Racket("Yonex", "Badminton", 89.0, 680.0, "Carbon Fiber", "Standard", 5700, "Purple", "Lee Chong Wei", 9);
System.out.println(r43.brand);
System.out.println(r43.type);
System.out.println(r43.weight);
System.out.println(r43.length);
System.out.println(r43.material);
System.out.println(r43.gripType);
System.out.println(r43.price);
System.out.println(r43.color);
System.out.println(r43.playerUsed);
System.out.println(r43.rating);

Racket r44 = new Racket("Head", "Tennis", 298.0, 684.0, "Graphite", "Pro Grip", 7900, "White", "Andy Murray", 10);
System.out.println(r44.brand);
System.out.println(r44.type);
System.out.println(r44.weight);
System.out.println(r44.length);
System.out.println(r44.material);
System.out.println(r44.gripType);
System.out.println(r44.price);
System.out.println(r44.color);
System.out.println(r44.playerUsed);
System.out.println(r44.rating);

Racket r45 = new Racket("Li-Ning", "Badminton", 86.5, 683.0, "Graphite", "Pro Grip", 6500, "Yellow", "Viktor Axelsen", 9);
System.out.println(r45.brand);
System.out.println(r45.type);
System.out.println(r45.weight);
System.out.println(r45.length);
System.out.println(r45.material);
System.out.println(r45.gripType);
System.out.println(r45.price);
System.out.println(r45.color);
System.out.println(r45.playerUsed);
System.out.println(r45.rating);

Racket r46 = new Racket("Babolat", "Tennis", 300.0, 688.0, "Aluminum", "Standard", 8250, "Black", "Roger Federer", 10);
System.out.println(r46.brand);
System.out.println(r46.type);
System.out.println(r46.weight);
System.out.println(r46.length);
System.out.println(r46.material);
System.out.println(r46.gripType);
System.out.println(r46.price);
System.out.println(r46.color);
System.out.println(r46.playerUsed);
System.out.println(r46.rating);

Racket r47 = new Racket("Yonex", "Badminton", 88.0, 681.0, "Carbon Fiber", "Standard", 5800, "Blue", "Carolina Marin", 9);
System.out.println(r47.brand);
System.out.println(r47.type);
System.out.println(r47.weight);
System.out.println(r47.length);
System.out.println(r47.material);
System.out.println(r47.gripType);
System.out.println(r47.price);
System.out.println(r47.color);
System.out.println(r47.playerUsed);
System.out.println(r47.rating);

Racket r48 = new Racket("Head", "Tennis", 299.0, 685.0, "Graphite", "Pro Grip", 8000, "White", "Rafael Nadal", 10);
System.out.println(r48.brand);
System.out.println(r48.type);
System.out.println(r48.weight);
System.out.println(r48.length);
System.out.println(r48.material);
System.out.println(r48.gripType);
System.out.println(r48.price);
System.out.println(r48.color);
System.out.println(r48.playerUsed);
System.out.println(r48.rating);

Racket r49 = new Racket("Li-Ning", "Badminton", 87.0, 684.0, "Graphite", "Pro Grip", 6600, "Red", "HS Prannoy", 9);
System.out.println(r49.brand);
System.out.println(r49.type);
System.out.println(r49.weight);
System.out.println(r49.length);
System.out.println(r49.material);
System.out.println(r49.gripType);
System.out.println(r49.price);
System.out.println(r49.color);
System.out.println(r49.playerUsed);
System.out.println(r49.rating);

Racket r50 = new Racket("Babolat", "Tennis", 301.0, 689.0, "Aluminum", "Standard", 8300, "Black", "Serena Williams", 10);
System.out.println(r50.brand);
System.out.println(r50.type);
System.out.println(r50.weight);
System.out.println(r50.length);
System.out.println(r50.material);
System.out.println(r50.gripType);
System.out.println(r50.price);
System.out.println(r50.color);
System.out.println(r50.playerUsed);
System.out.println(r50.rating);

}

}